services:
  - type: web
    name: arthos-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: bd
    buildCommand: bash build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
