services:
  - type: web
    name: arthos-backend
    env: python
    pythonVersion: "3.11.9"
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: CARGO_HOME
        value: /opt/render/project/.cargo
      - key: RUSTUP_HOME
        value: /opt/render/project/.rustup
      - fromGroup: arthos-db-credentials
      - fromGroup: arthos-secret-keys
      - fromGroup: arthos-gemini-key
